### ISSUE TITLE
Are you using a conditional adversarial network for image inpainting?

### ISSUE THREAD

**Issue by cuevas1208** [NVIDIA/partialconv#12]
![image](https://user-images.githubusercontent.com/13240742/54218968-c95e2f00-44ab-11e9-9cc9-212d048862e7.png)

When I was reading the paper reference 11 is Isola, P., Zhu, J.Y., Zhou, T., Efros, A.A.: Image-to-image translation with conditional adversarial networks. arXiv preprint (2017).

Are you using a conditional adversarial network?

**Comment by liuguilin1225** [comment]
No. GAN is not used. We just said the network is similar to the the UNet(generator part) in [11]. The network detail can be found in Table 2 and the loss function can also be found in Section 3.3

**Comment by cuevas1208** [comment]
thanks

**Comment by cuevas1208** [comment]
As shown below, I used the web application for inpainting, I mask a person and then an HD face came out. Is that face generated with partial convolution inpainting or GAN. how did the algorithm decide to create a high definition face but a body as a blurred background? can you explain that to me?

![image](https://user-images.githubusercontent.com/13240742/54314513-1b30b300-4599-11e9-9414-6ac6a79d92c8.png)


![image](https://user-images.githubusercontent.com/13240742/54314420-d9077180-4598-11e9-83ff-ecfd8a562065.png)

**Comment by liuguilin1225** [comment]
The reason is that currently we assume that for faces, users are editing the faces instead of completely removing the faces. In this implementation, we have two models: one for face inpainting, one for natural image inpainting. The processing pipeline for this online demo is:
1. use a face detector (non-DL based) to detect all the face regions;
2. for face regions, we use face inpainting model to do the editing; for non-face regions, we use natural image inpainting model to do the editing. 
This explains why if you mask out the face region, it will generate anew face there. You can mask out the face region first before uploading it.

**Comment by cuevas1208** [comment]
OK, that make sense. Thank you for your quick reply

**Comment by FloCF** [comment]
Hey! Great work.
I was wondering if you are feeding your model for face inpainting with any additional information, like landmarks or so? Because it looks like position of nose, eyes and face rotation are quite similar to ground truth in the result above.

**Comment by liuguilin1225** [comment]
@FloCF we have a third-party face landmark detector to detect landmarks for this online demo.

**Comment by hiterjoshua** [comment]
@liuguilin1225 Thanks for your great job! the inpainting result from online demo is better than the reproduced partial convolution model, now I know there are some progress from partial convolution to online demo. I am still wandering how did you use the face landmarks in your network? I didnot see some flexible interfaces in partial network, so how did you use those information?
Thanking for your time.
