### ISSUE TITLE
Doesn't take 2 channel mask as input

### ISSUE THREAD

**Issue by NagabhushanSN95** [NVIDIA/partialconv#31]
Hi,

In your inpainting paper, you've mentioned that in the decoder part of  Unet, you add skip connections for both features and mask by concatenating them. I assume you concatenate them along feature channels. But if I give this concatenated mask as input to the Pconv layer, it throws the following error. So, it looks like I can't pass the concatenated mask to this layer directly. What should I concatenate the masks?

```
RuntimeError: Given groups=1, weight of size [1, 1, 3, 3], expected input[8, 2, 32, 32] to have 1 channels, but got 2 channels instead
```

**Comment by liuguilin1225** [comment]
For my implementation, instead of setting mask channel account to be 1, I set it to be the same channel account as image's feature channel account. That means if my feature is with the shape of [8, 64, 32, 32], my mask will also be with the shape of [8, 64, 32, 32].
This is just the naive implementation costing more memory. There should be some more memory-efficient way.

**Comment by NagabhushanSN95** [comment]
Cool. Thanks for the quick reply. I assume, you achieve this by setting `multi_channel=True`. I tried that and it is working. 

I tried to change the partialconvolution2d.py code to set input channels to 2 when multi_channel=True (to reduce memory usage), but it gave some error. So, I left it there.
