### ISSUE TITLE
Does the order of applying mask matter?

### ISSUE THREAD

**Issue by hughplay** [NVIDIA/partialconv#6]
When I check the implementation of `PartialConv2d`, I find you apply updated mask after a normal convolution rather than apply mask to input first:

https://github.com/NVIDIA/partialconv/blob/90306f1475aaeb94f34d57b1f6d1833ee2f8f81b/models/partialconv2d.py#L75

I'm curious about whether these two ways have difference? It seems applying mask first is faster in intuition.

**Comment by hughplay** [comment]
After imitating the whole processing within brain, I think it seems have some problem here.

https://github.com/NVIDIA/partialconv/blob/90306f1475aaeb94f34d57b1f6d1833ee2f8f81b/models/partialconv2d.py#L70

If you don't mask the input before the normal convolution, the result will contain the information from hole area. Except you make sure the hole area of input is always zero.

But the idea of considering the padding area as mask to avoid re-weighted problem is awesome.

**Comment by liuguilin1225** [comment]
@hughplay Thanks a lot for your comments. 
For the first question: we need to apply the mask after we add the bias since we want the hole regions to have 0 values instead of values == bias. 
For the second question, I have updated the code to incorporate your comments. Yes, it is better to mask the input at the begin. The reason why I didn't do that is that for the original raw input, I would always set the values to be 0; the partial conv layer would also set the un-filled regions to have value 0 as the outputs. But it is better to mask the input first to be safe in case the input's hole values are not set to be 0.

**Comment by hughplay** [comment]
Ok, great! I also make it clear after implementing it by my self. Thanks for your nice work!
